import { chromium } from "@playwright/test";
const base = process.env.BASE ?? "http://localhost:3100";
const out = process.env.OUT ?? "/tmp/claude-0/-home-user-dr-jena-site/022df62b-8220-5f8e-a0f7-3870942c9ff7/scratchpad";
const browser = await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM_PATH ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_PATH } : {});
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
await page.goto(base + "/login");
await page.getByTestId("login-email").fill("admin@demo.local");
await page.getByTestId("login-password").fill("Demo1234!");
await page.getByTestId("login-submit").click();
await page.waitForURL(/dashboard/, { timeout: 60000 });
await page.screenshot({ path: `${out}/mobile-dashboard.png` });
await page.getByTestId("mobile-nav-open").click();
await page.getByTestId("mnav-jobs").waitFor();
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/mobile-drawer.png` });
await page.getByTestId("mnav-jobs").click();
await page.waitForURL(/jobs/);
await page.screenshot({ path: `${out}/mobile-jobs.png` });
console.log("mobile ok");
await browser.close();
