/** Demo company profile (Dr.Jena) — pure data, shared by the seed and the browser demo. */
export const DEMO_PROFILE = {
  companyName: "Dr.Jena Creative & AI Marketing",
  tagline: "30年の美意識で、ブランドを育てる。Web制作 × AIマーケティング × マーケットデザイン",
  services: "コーポレートサイト制作、LP制作、SaaS/Webアプリ開発、AIチャットボット・生成AI活用支援、SNS/広告運用、SEO、ブランディング・デザイン、動画制作、EC構築、DXコンサルティング",
  strengths: ["ブランディング起点の設計", "生成AIを活用した高速制作", "多言語対応（日英中韓）", "美容・ヘルスケア領域の深い知見", "小規模でも一気通貫で対応"],
  weaknesses: ["ネイティブアプリ開発", "大規模基幹システム", "ハードウェア"],
  capabilities: ["Web Development", "SaaS", "AI", "Marketing", "Design", "Video", "EC", "SEO", "Automation", "Consulting", "Next.js", "React", "TypeScript", "WordPress", "Shopify", "Tailwind CSS", "PostgreSQL", "Prisma", "Claude API", "RAG", "Python", "Landing Page", "Branding", "Figma", "Instagram", "Meta Ads", "Google Ads", "Content Marketing", "Zapier", "Make", "Slack API", "DX", "Roadmap"],
  priceRange: "USD 1,500 – 40,000 / project",
  minimumOrderPrice: 1000,
  currency: "USD",
  hourlyRate: 85,
  achievements: [
    { title: "原宿の美容サロン向けコーポレートサイト刷新（問い合わせ2.3倍）", description: "ブランディング起点でサイト全面リニューアル。CVR改善で問い合わせ数2.3倍。", metric: "+130% inquiries", category: "Web Development" },
    { title: "化粧品D2CブランドのShopify構築と定期購入導入", description: "120SKUのECサイト構築、定期購入・CRM連携。", metric: "LTV +40%", category: "EC" },
    { title: "クリニック向けAI問い合わせボット（FAQ 80件・日英対応）", description: "Claude APIとRAGで問い合わせ自動応答、有人エスカレーション付き。", metric: "-60% response time", category: "AI" },
    { title: "美容機器メーカーのSNS・広告運用（12ヶ月）", description: "Instagram/LINE/Meta広告の統合運用、月次レポート。", metric: "ROAS 3.8", category: "Marketing" },
    { title: "旅館グループのブランドムービー制作（日英字幕）", description: "60秒ブランドムービー＋SNSカット。", metric: "1.2M views", category: "Video" },
    { title: "食品メーカーの受注〜請求自動化（kintone/Slack）", description: "Make + スクリプトで業務自動化、月40時間削減。", metric: "-40h/month", category: "Automation" },
    { title: "美容サロンのDXロードマップ策定", description: "3部門ヒアリング、12ヶ月ロードマップ。", metric: "12-month roadmap", category: "Consulting" },
  ],
  portfolio: [
    { title: "Dr.Jena Corporate Site", url: "https://jiantailanglin266-rgb.github.io/dr-jena-site/", description: "Brand-first corporate site with cinematic hero video", category: "Web Development" },
    { title: "AI Marketing Service Page", url: "https://jiantailanglin266-rgb.github.io/dr-jena-site/ai-marketing.html", description: "Service, pricing plans and process", category: "Marketing" },
    { title: "Beauty Brand Page (JenaPro)", url: "https://jiantailanglin266-rgb.github.io/dr-jena-site/beauty.html", description: "Product storytelling page", category: "Design" },
  ],
  caseStudies: [{ title: "問い合わせ2.3倍のサイト刷新", problem: "古いサイトでスマホ離脱が多い", solution: "ブランド再定義 → 情報設計 → 高速なNext.js実装", result: "問い合わせ2.3倍、直帰率-35%" }],
  differentiators: ["美容ブランド運営30年の審美眼", "生成AIワークフローによる短納期", "設計〜運用まで一社完結"],
  languages: ["ja", "en", "zh", "ko"],
  availableHours: "JST 10:00–19:00（月〜金）、緊急時は応相談",
  typicalLeadTime: "LP 2週間 / コーポレートサイト 4〜6週間 / SaaS MVP 8〜12週間",
  staffCount: 8,
  techStack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "PostgreSQL", "Prisma", "WordPress", "Shopify", "Claude API", "OpenAI API", "Python", "Make", "Zapier", "Figma", "Premiere Pro"],
  pastProjects: [],
  faq: [
    { q: "納品後のサポート期間はどのくらいですか？", a: "納品後30日間の無償サポート（軽微な修正・不具合対応）を標準で含みます。以降は月額保守プランをご用意しています。" },
    { q: "修正は何回まで可能ですか？", a: "各工程で2回までの修正を標準としています。追加は実費でご相談可能です。" },
    { q: "着手までに準備するものは？", a: "原稿・写真・ロゴなどの素材、既存アカウント情報、要件のご担当者をご指定ください。" },
    { q: "進捗はどのように共有されますか？", a: "週次のオンライン定例と、Slack/メールでの随時報告で共有します。" },
    { q: "既存システムとのAPI連携は可能ですか？", a: "可能です。REST/GraphQL/Webhook いずれにも対応し、認証・暗号化を含めたセキュリティ設計を行います。" },
    { q: "How do you guarantee quality?", a: "Every phase has a review checkpoint, we ship a staging environment for acceptance, and we include a 30-day post-launch support window. If you are not satisfied at the requirements stage, you can stop with no further obligation." },
    { q: "Can our in-house engineers maintain it afterwards?", a: "Yes — we use mainstream stacks (Next.js/TypeScript/PostgreSQL) and deliver documentation plus a handover session." },
  ],
  forbiddenConditions: ["成果報酬のみ", "revenue share only", "無償トライアル", "アダルト", "gambling"],
  excludeKeywords: ["adult", "casino", "crypto pump", "MLM"],
  priorityKeywords: ["美容", "beauty", "クリニック", "clinic", "ブランド", "brand", "AI", "Shopify"],
};

