import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CheckCircle2, MessagesSquare, ExternalLink, Building2 } from "lucide-react";
import { requireSession } from "@/lib/auth";
import { getDeal } from "@/lib/services/crm";
import { DEAL_CHECKLIST } from "@/lib/agents/closing";
import { PageHeader, KV, Flag, ScoreRing } from "@/components/ui/misc";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge, StatusBadge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DealApproval, type ChecklistRow } from "@/components/crm/deal-approval";
import { dec, formatCurrency, formatDateTime, formatPct } from "@/lib/utils";

interface DealSummaryJson {
  narrative?: string;
  confidence?: number;
  unresolved?: string[];
  notes?: string | null;
  deliverables?: string[];
}

export default async function DealDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireSession();
  const { id } = await params;
  const deal = await getDeal(user.orgId, id);
  if (!deal) notFound();

  const summary = ((deal.summary ?? {}) as DealSummaryJson) || {};
  const stored = Array.isArray(deal.checklist) ? (deal.checklist as unknown as Partial<ChecklistRow>[]) : [];
  const checklist: ChecklistRow[] = DEAL_CHECKLIST.map((c) => {
    const s = stored.find((x) => x?.key === c.key);
    return { key: c.key, label: s?.label ?? c.label, confirmed: Boolean(s?.confirmed), value: s?.value != null ? String(s.value) : null };
  });
  const unresolved = Array.isArray(summary.unresolved) ? summary.unresolved : [];
  const confidence = typeof summary.confidence === "number" ? Math.round(summary.confidence) : null;
  const won = deal.status === "WON";
  const job = deal.opportunity.job;
  const conv = deal.opportunity.conversation;

  return (
    <>
      <PageHeader
        title={deal.title}
        description={`${job.projectTitle} · ${job.platformKey}`}
        actions={
          <>
            <Button variant="ghost" size="sm" asChild>
              <Link href="/crm/deals">
                <ArrowLeft /> Deals
              </Link>
            </Button>
            {conv ? (
              <Button variant="outline" size="sm" asChild>
                <Link href={`/conversations/${conv.id}`}>
                  <MessagesSquare /> Conversation
                </Link>
              </Button>
            ) : null}
            <Button variant="outline" size="sm" asChild>
              <Link href={`/jobs/${job.id}`}>
                <ExternalLink /> Job
              </Link>
            </Button>
          </>
        }
      />

      {won ? (
        <div className="mb-6 flex flex-wrap items-center gap-3 rounded-xl border border-success/30 bg-success-soft px-4 py-3 text-sm" data-testid="deal-won-banner">
          <CheckCircle2 className="size-4 text-success" />
          <span className="font-medium text-success">Deal WON</span>
          <span className="text-xs text-muted-foreground">
            Approved by <span className="font-medium text-foreground">{deal.approvedBy?.name ?? "—"}</span>
            {deal.wonAt ? <> · {formatDateTime(deal.wonAt)}</> : null}
            {" · "}{formatCurrency(dec(deal.amount), deal.currency)} ({formatCurrency(dec(deal.amountUsd), "USD")})
          </span>
        </div>
      ) : deal.status === "LOST" ? (
        <div className="mb-6 flex items-center gap-3 rounded-xl border border-danger/30 bg-danger-soft px-4 py-3 text-sm">
          <span className="font-medium text-danger">Deal LOST</span>
          {deal.lostAt ? <span className="text-xs text-muted-foreground">{formatDateTime(deal.lostAt)}</span> : null}
        </div>
      ) : null}

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
        <div className="flex flex-col gap-6">
          <Card>
            <CardHeader className="flex-row items-start justify-between gap-4">
              <div>
                <CardTitle>Deal Summary</CardTitle>
                <CardDescription>Generated by the Closing Agent from the full thread. Verify each term before approval.</CardDescription>
              </div>
              {confidence !== null ? <ScoreRing score={confidence} size={48} label="confidence" /> : null}
            </CardHeader>
            <CardContent className="flex flex-col gap-4">
              {summary.narrative ? <p className="whitespace-pre-wrap text-sm leading-relaxed">{summary.narrative}</p> : <p className="text-xs text-muted-foreground">No narrative available.</p>}
              {unresolved.length ? (
                <div className="flex flex-wrap items-center gap-1.5 text-xs">
                  <span className="text-muted-foreground">Unresolved:</span>
                  {unresolved.map((u) => (
                    <Badge key={u} variant="warning">{u.replace(/_/g, " ")}</Badge>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-success">No unresolved items flagged by AI.</p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex-row items-center justify-between">
              <div>
                <CardTitle>Checklist &amp; approval</CardTitle>
                <CardDescription>All 9 items must be confirmed by a human before the deal can be marked WON.</CardDescription>
              </div>
              <span data-testid="deal-status"><StatusBadge status={deal.status} /></span>
            </CardHeader>
            <CardContent>
              <DealApproval dealId={deal.id} status={deal.status} currency={deal.currency} amount={dec(deal.amount)} notes={summary.notes ?? ""} checklist={checklist} unresolved={unresolved} />
            </CardContent>
          </Card>
        </div>

        <aside className="flex flex-col gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Amount</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-2xl font-semibold tabular-nums tracking-tight">{formatCurrency(dec(deal.amount), deal.currency)}</p>
              <p className="text-xs text-muted-foreground">{formatCurrency(dec(deal.amountUsd), "USD")}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Client</CardTitle>
            </CardHeader>
            <CardContent className="divide-y divide-border">
              <KV k="Name" v={deal.client ? <Link href={`/crm/companies/${deal.client.id}`} className="flex items-center gap-1 hover:underline"><Building2 className="size-3" /> {deal.client.name}</Link> : job.clientName ?? "—"} />
              <KV k="Country" v={<span className="flex items-center gap-1.5"><Flag country={job.clientCountry} /> {job.clientCountry ?? "—"}</span>} />
              <KV k="Language" v={job.clientLanguage ?? "—"} />
              <KV k="Platform" v={job.platformKey} />
              <KV k="Lead status" v={<StatusBadge status={deal.opportunity.status} />} />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Quotes</CardTitle>
              <CardDescription>{deal.opportunity.quotes.length ? `${deal.opportunity.quotes.length} version${deal.opportunity.quotes.length === 1 ? "" : "s"}` : "No quotes"}</CardDescription>
            </CardHeader>
            {deal.opportunity.quotes.length ? (
              <CardContent>
                <ul className="divide-y divide-border">
                  {deal.opportunity.quotes.map((q) => (
                    <li key={q.id} className="flex flex-col gap-1 py-2 text-xs">
                      <div className="flex items-center justify-between gap-2">
                        <span className="font-medium">v{q.version} · {formatCurrency(dec(q.totalAmount), q.currency)}</span>
                        <StatusBadge status={q.status} />
                      </div>
                      <div className="flex flex-wrap gap-x-3 text-[11px] text-muted-foreground">
                        <span>discount {formatPct(dec(q.discountPct), 0)}</span>
                        {q.deliveryDays ? <span>{q.deliveryDays}d</span> : null}
                        {q.paymentTerms ? <span>{q.paymentTerms}</span> : null}
                      </div>
                    </li>
                  ))}
                </ul>
              </CardContent>
            ) : null}
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Timeline</CardTitle>
            </CardHeader>
            <CardContent className="divide-y divide-border">
              <KV k="Created" v={formatDateTime(deal.createdAt)} />
              <KV k="Updated" v={formatDateTime(deal.updatedAt)} />
              <KV k="Approved" v={deal.approvedAt ? formatDateTime(deal.approvedAt) : "—"} />
              <KV k="Won" v={deal.wonAt ? formatDateTime(deal.wonAt) : "—"} />
            </CardContent>
          </Card>
        </aside>
      </div>
    </>
  );
}
